### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by jarodium** [prbdias/mbway-php#1]
Hello

Can you provide more examples?

**Comment by prbdias** [comment]
Which type of examples are you looking for? 
I gave an example for the two different allowed methods.
Let me know if I am missing something I'd be more than happy to help you.

**Comment by prbdias** [comment]
I think I know which kind of examples you are looking for.
I've some examples on the tests as well.
If you didn't find what you're looking for there just let me know.

**Comment by jarodium** [comment]
The examples on the tests do not display the proper workflow ( or I have misunderstood something ) and some resolve in error.

[at1.txt](https://github.com/prbdias/mbway-php/files/64050/at1.txt)

The code in the attached field yields the following error:
[Wed Dec 16 13:51:08 2015] [error] [client 85.244.90.184] PHP Fatal error:  Class 'prbdias\mbway\Alias' not found in at1.php on line 21

**Comment by jarodium** [comment]
Regarding the example for the AsyncService I have found the following issue:

Sat Jan 09 13:55:11 2016] [error] [client 85.244.90.184] PHP Catchable fatal error:  Argument 1 passed to prbdias\mbway\MBWayAsyncService::createFinancialOperationAsyncResultService() must be an instance of prbdias\mbway\callable, instance of Closure given, called in /var/www/index.php on line 13 and defined in /var/www/vendor/prbdias/mbway-php/src/prbdias/mbway/MBWayAsyncService.php on line 17

**Comment by prbdias** [comment]
Hi @jarodium,

Sorry for the late response but I've been really busy lately.
Which version of PHP are you using?
This library just supports PHP5.4+ and for the error log you just shared I would say you are using a PHP version between 5.3.21 and 5.3.29.

Please, try it by yourself :)
https://3v4l.org/kqeYD#v5321

**Comment by jarodium** [comment]
Hello @prbdias 

Since then I was able to upgrade to a new machine powered by 5.4, but since I am doing some relocation for sites in the older server I was not able to re-test the library.
When I have time, I will test her again.

Thanks for the reply

**Comment by jarodium** [comment]
Hello 
I'm starting to use your library with PHP 5.4 at this time, error log shows this:

[23-Dec-2016 13:33:21 UTC] PHP Notice:  Use of undefined constant SOAP_SSL_METHOD_TLS - assumed 'SOAP_SSL_METHOD_TLS' in /vendor/prbdias/mbway-php/src/prbdias/mbway/MBWayClient.php on line 122
[23-Dec-2016 13:33:21 UTC] PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in /vendor/prbdias/mbway-php/src/prbdias/mbway/MBWayClient.php:186
Stack trace:
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://qly.mbw...', '', 1, 0)
#1 /vendor/prbdias/mbway-php/src/prbdias/mbway/MBWayClient.php(186): SoapClient->__soapCall('requestFinancia...', Array, Array)
#2 /pagar.php(32): prbdias\mbway\MBWayClient->requestFinancialOperation(Object(prbdias\mbway\FinancialOperation\RequestFinancialOperation))
#3 {main}
  thrown in /vendor/prbdias/mbway-php/src/prbdias/mbway/MBWayClient.php on line 186

IP Address from the server is already allowed in SIBS system. I don't implicity use 'use ....\SoapClient' since PHP supports it.

Code is as follows:

```php
<?
    require 'vendor/autoload.php';
    use prbdias\mbway\Config;
    use prbdias\mbway\Alias;
    use prbdias\mbway\FinancialOperation;
    use prbdias\mbway\FinancialOperation\RequestFinancialOperation;
    use prbdias\mbway\FinancialOperation\RequestFinancialOperationRequest;
    use prbdias\mbway\MBWayClient;
    use prbdias\mbway\Merchant;
    use prbdias\mbway\MessageProperties;
    
    $ssl_cert = "MCERT.p12";
    $ssl_pass = "THEPASS";
    
    $merchantAlias = "HOST/CreateMerchantAliasAsyncResultService";
    $financialOps = "HOST/CreateFinancialOperationAsyncResultService";
    
    $config = new Config($ssl_cert, $ssl_pass, $merchantAlias, $financialOps, $MERCHID, $_SERVER["SERVER_ADDR"]);
    var_dump($config);
    $test = new RequestFinancialOperation();
    $operation = new FinancialOperation();
    $operation->setAmount(2.00)
        ->setCurrencyCode(9782)
        ->setMerchantOprId(uniqid())
        ->setOperationTypeCode(FinancialOperation::PURCHASE_AUTHORIZATION);
    $request = new RequestFinancialOperationRequest();
    $request->setFinancialOperation($operation);
    $test->setArg0($request);
    
    $service = new MBWayClient($config);
    $service->setSandbox(true);
    $response = $service->requestFinancialOperation($test);
    $return = $response->getReturn();
    
    var_dump($return);
?>
```

**Comment by prbdias** [comment]
Sorry, completely my bad by not having the PHP minimum version requirement. It is actually necessary PHP 5.5 to use the constant SOAP_SSL_METHOD_TLS.
