### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by RobsonIT** [prbdias/mbway-php#4]
Hi Paulo

For several days, I have a problem with connecting to the MBWay server by prbdias/mbway-php

The certificate and password used seems to be correct, because in SoapUI after configuring the request there is a response from the server.

I have prepared a minimalist script that contains this error, it is available here https://pastebin.com/h07k299B

Would you have time and willingness to look at this case?

Please feel free to ask if anything is unclear.

Regards Robert

**Comment by prbdias** [comment]
@ct2glx Do you think this issue could be related with the one you faced recently?

**Comment by ct2glx** [comment]
Yes @prbdias , that is related with the updates in the SSL protocols SIBS is accepting, you just need to update the SLL METHOD in the MBWayClient.php to  'ssl_method'    => SOAP_SSL_METHOD_SSLv23.
in the meantime MBWay has added some new services that are kind of underdocumented... no WSDLs, i have updated the WSDLs in my fork and added support for one of them (and i think will do the same for the other), then i will make a pull request... in the meantime, to overcome that problem you only need to update that constant and it will connect :)

**Comment by ct2glx** [comment]
@RobsonIT checked your code, you need to convert the ssl cert to PEM, PHP SOAP client does not accept PFX.

Ping-me if you need help, i'm implementing MBWay just now, so you might have the same doubts.

**Comment by RobsonIT** [comment]
Yes, works great, i checked before SOAP_SSL_METHOD_SSLv23 but on PFX file. I've got tutorial from SIBS to export from p12 to pfx file.
Moreover this pfx file works on SoapUI so i thought its ok wtith file, and im started looking somewhere else.

Thanks a lot
